### ISSUE TITLE
apply passport library

### ISSUE THREAD

**Issue by heartyoh** [things-factory/auth-base#1]
http://www.passportjs.org/

**Comment by lotstar87** [comment]
# Passport 적용으로 기대되는 효과
google, github, facebook등의 인증을 적용하기 위해 많은 코드를 수정할 필요가 없어짐.

하지만 jwt만 사용하는 현재로써는 기대할 수 있는 부분은 없음.

**Comment by lotstar87** [comment]
token이 존재하지만 유효하지 않거나 접속정보가 일치하지 않는 경우에 대한 문제 처리 필요
